package se.lexicon.reference.component.entity;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.component.entity.AbstractEntityBuilder;
import com.so4it.component.entity.IdEntity;

import java.util.Currency;

@SpaceClass
public class InstrumentEntity extends IdEntity<String> {


    //The unique id
    @Allowed(value = "Auto generated by GS", types = {Allowed.Type.NULLABLE})
    private String id;
    //The arrangement id of this account balance
    private String name;

    private Currency currency;

    private InstrumentEntity() {
    }

    private InstrumentEntity(Builder builder) {
        this.id = builder.id;
        this.name = Required.notNull(builder.name, "name", builder.isTemplate());
        this.currency = Required.notNull(builder.currency, "currency", builder.isTemplate());
    }

    // @SpaceRouting = routing for GS
    // @Routing = routing for so4it

    @Override
    @SpaceId(autoGenerate = true)
    // @SpaceRouting
    public String getId() {
        return id;
    }

    private void setId(String id) {
        this.id = id;
    }

    @SpaceRouting
    public String getName() {
        return name;
    }

    private void setName(String name) {
        this.name = name;

    }

    public Currency getCurrency() {
        return currency;
    }

    private void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public static Builder builder() {
        return new Builder(false);
    }

    public static Builder templateBuilder() {
        return new Builder(true);
    }

    //
    public static class Builder extends AbstractEntityBuilder<InstrumentEntity> {

        private String id;
        private String name;
        private Currency currency;

        public Builder(boolean template) {
            super(template);
        }

        public InstrumentEntity.Builder withId(String id) {
            this.id = id;
            return this;
        }

        public InstrumentEntity.Builder withName(String name) {
            this.name = name;
            return this;
        }

        public InstrumentEntity.Builder withCurrency(Currency currency) {
            this.currency = currency;
            return this;
        }

        @Override
        public InstrumentEntity build() {
            return new InstrumentEntity(this);
        }
    }
}